// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace standby_data.Models;

public partial class tb_clientes
{
    [Key]
    public int cl_id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string cl_nome { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string cl_telefone { get; set; }

    [Required]
    [StringLength(18)]
    [Unicode(false)]
    public string cl_cpf { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string cl_telefone_recado { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string cl_nome_recado { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cl_parentesco_recado { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string cl_sexo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? cl_data_nascimento { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string cl_cep { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string cl_endereco { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string cl_complemento { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cl_bairro { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cl_cidade { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string cl_estado { get; set; }

    [InverseProperty("sv_cl_idclienteNavigation")]
    public virtual ICollection<tb_servicos> tb_servicos { get; } = new List<tb_servicos>();
}