// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace standby_data.Models
{
    public partial class tb_clientes
    {
        public tb_clientes()
        {
            tb_servicos = new HashSet<tb_servicos>();
        }

        [Key]
        public int cl_id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string cl_nome { get; set; }
        [Required(ErrorMessage = "Voce deve preencher um numero de telefone")]
        [StringLength(15, ErrorMessage = "Telefone principal invalido, preencha corretamente")]
        [Unicode(false)]
        public string cl_telefone { get; set; }
        [Required]
        [StringLength(18)]
        [MinLength(14, ErrorMessage = "O número de CPF/CNPJ deve ter pelo menos 14 dígitos.")]
        [Unicode(false)]
        public string cl_cpf { get; set; }
        [Required(ErrorMessage = "Voce deve preencher um numero de telefone para recado")]
        [StringLength(100)]
        [Unicode(false)]
        public string cl_telefone_recado { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string cl_nome_recado { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string cl_parentesco_recado { get; set; }
        [StringLength(1, ErrorMessage = "O Sexo deve possuir apenas 1 letra")]
        [Unicode(false)]
        public string cl_sexo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? cl_data_nascimento { get; set; }
        [StringLength(10)]
        [MinLength(9, ErrorMessage = "CEP deve ter nenhum ou pelo menos 9 digitos")]
        [Unicode(false)]
        public string cl_cep { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string cl_endereco { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string cl_complemento { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string cl_bairro { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string cl_cidade { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string cl_estado { get; set; }

        [InverseProperty("sv_cl_idclienteNavigation")]
        public virtual ICollection<tb_servicos> tb_servicos { get; set; }
    }
}