// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace standby_data.Models;

public partial class tb_comp_items
{
    [Key]
    public int item_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string item_tela { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string item_grupo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string item_nome { get; set; }

    public bool? item_editavel { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string item_texto { get; set; }
}